# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
curator:
  app:
    unit: days
    count: 14
elasticsearch:
  data:
    replicas: 1
    storage:
      "persistent": true
      #size: 30Gi
logstash:
  replicas: 1
kibana:
  replicas: 1
