# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
logstash:
  image:
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/icp-logstash-oss
    digest:
kibana:
  image:   
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/icp-kibana-oss
    digest:
  initImage:
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/curl
    digest:
  #routerImage:
    #repository: "quay.io/opencloudio/icp-management-ingress"
    #tag: "2.5.3"
    #digest:
filebeat:
  image:
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/icp-filebeat-oss
    digest:
elasticsearch:
  image:
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/icp-elasticsearch-oss
    digest:
  initImage:
    repository: "hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/icp-initcontainer"
    #tag: "1.0.0-build.6"
    digest: ""
  pkiInitImage:
    repository: "hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/logging-pki-init"
    #tag: "2.3.0-build.4"
    digest:
  routerImage:
    repository: "quay.io/opencloudio/icp-management-ingress"
    tag: "2.5.3"
    #digest:
curator:
  image:
    repository: "hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/indices-cleaner"
    digest:
