#
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
logstash:
  image:
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/icp-logstash-oss
    digest:
kibana:
  image:   
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/icp-kibana-oss
    digest:
  initImage:
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/curl
    digest:
  #routerImage:
    #repository: "quay.io/opencloudio/icp-management-ingress"
    #tag: "2.5.3"
    #digest:
filebeat:
  image:
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/icp-filebeat-oss
    digest:
elasticsearch:
  image:
    repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/icp-elasticsearch-oss
    digest:
  initImage:
    repository: "hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/icp-initcontainer"
    #tag: "1.0.0-build.6"
    digest: ""
  pkiInitImage:
    repository: "hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/logging-pki-init"
    #tag: "2.3.0-build.4"
    digest:
  routerImage:
    repository: "quay.io/opencloudio/icp-management-ingress"
    tag: "2.5.3"
    #digest:
curator:
  image:
    repository: "hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/indices-cleaner"
    digest:
