# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-curator-config"
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app .Values.curator.name "config") | indent 4 }}
data:
  action.yml: |-
{{ tpl (.Files.Get "curator/action.yml") . | indent 4 }}
  config.yml: |-
{{ tpl (.Files.Get "curator/config.yml") . | indent 4 }}
