# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-config"
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app .Values.elasticsearch.data.name "config") | indent 4 }}
data:
  data.yml: |-
{{ tpl (.Files.Get "elasticsearch/general.config") . | indent 4 }}
    node.master: true
    node.data: true
    path.data: /usr/share/elasticsearch/data/6.x
