{{ template "elk.settings.all.prepare" . -}}
{{- if .Values.general.pkiInitEnabled }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-pki-secret"
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app "pki-init" "init") | indent 4 }}
type: Opaque
data:
  caKeystorePassword: "{{ .Values.security.ca.keystore.password | b64enc }}"
  caTruststorePassword: "{{ .Values.security.ca.truststore.password | b64enc }}"
  appKeystorePassword: "{{ .Values.security.app.keystore.password | b64enc }}"
{{- end }}
