{{ template "elk.settings.all.prepare" . -}}
{{- if .Values.general.pkiInitEnabled }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "elasticsearch.fullname" . }}-pki-delete"
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app "secret-delete" "cleanup") | indent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": "hook-succeeded, before-hook-creation"
    "helm.sh/hook-weight": "-9"
spec:
  template:
    metadata:
      labels:
{{ include "metadata.calculateLabels" (list . $app "secret-delete" "cleanup") | indent 8 }}
      annotations:
{{ include "metadata.calculateAnnotations" (list . ) | indent 8 }}
    spec:
{{ include "image.pullSecret" . | indent 6 }}
      serviceAccountName: "{{ template "job.fullname" . }}"
      containers:
      - name: kubectl
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsNonRoot: true
        image: {{ include "image.calculateImage" (list .Values.elasticsearch.pkiInitImage.repository .Values.elasticsearch.pkiInitImage.tag .Values.elasticsearch.pkiInitImage.digest) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.elasticsearch.pkiInitImage.resources | indent 12 }}
        command: ['/bin/sh']
        args: ['-c', 'kubectl delete secret {{ template "fullname" . }}-certs --ignore-not-found=true && kubectl delete secret {{ template "elasticsearch.fullname" . }}-pki-secret --ignore-not-found=true && kubectl delete secret {{ template "fullname" . }}-ca --ignore-not-found=true && kubectl delete secret {{ template "kibana.fullname" . }}-init-secret --ignore-not-found=true && kubectl delete secret {{ template "kibana.fullname" . }}-nginx --ignore-not-found=true']
      restartPolicy: Never
{{- end }}
