{{ template "elk.settings.all.prepare" . -}}
{{- if .Values.general.pkiInitEnabled }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app "pki-init" "init") | indent 4 }}
  name: "{{ template "elasticsearch.fullname" . }}-pki-init-binding"
  annotations:
subjects:
- kind: ServiceAccount
  name: {{ template "job.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "elasticsearch.fullname" . }}-pki-init
  apiGroup: rbac.authorization.k8s.io
{{- end }}
