# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app "tls-delete" "cleanup") | indent 8 }}
  name: {{ template "elasticsearch.fullname" . }}-tls-cleanup
data:
  cleanup.sh: |-
{{ tpl (.Files.Get "es-tls-cleanup/cleanup.sh") . | indent 4 }}
