{{- if (.Values.kibana.install) }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kibana.fullname" . }}-init-secret
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app .Values.kibana.name "init") | indent 4 }}
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
    ibm.com/iam-service.id: "kibana-init-{{ $.Release.Name }}-service-id"
    ibm.com/iam-service.api-key: "kibana-init-{{ $.Release.Name }}-api-key"
    ibm.com/iam-service.name: "kibana-init-{{ $.Release.Name }}-service"
type: Opaque
data:
{{ end }}
