{{- if .Values.kibana.install -}}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "kibana.fullname" . }}-config"
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app .Values.kibana.name "kibana") | indent 4 }}
data:
  kibana.yml: |-
{{ tpl (.Files.Get "kibana/kibana.yml") . | indent 4 }}
{{- end }}
