{{- if .Values.kibana.install }}
{{ template "elk.settings.all.prepare" . -}}
{{- if .Values.kibana.routerEnabled }}
# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Secret
metadata:
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app .Values.kibana.name "proxy") | indent 4 }}
  name: "{{ template "kibana.fullname" . }}-nginx"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-4"
data:
  client-api-key: |-
    {{ uuidv4 | b64enc }}
{{- end }}
{{- end }}
