# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  labels:
{{ $app := include "elasticsearch.fullname" . -}}
{{ include "metadata.calculateLabels" (list . $app .Values.logstash.name "network") | indent 4 }}
  name: "{{ .Values.logstash.name }}"
spec:
  ports:
  - name: "beats"
    port: {{ .Values.logstash.port }}
    targetPort: {{ .Values.logstash.port }}
  selector:
    app: "{{ template "elasticsearch.fullname" . }}"
    component: "{{ .Values.logstash.name }}"
    role: "logstash"
