# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

filebeat.config:
  inputs:
    # Mounted `filebeat-inputs` configmap:
    path: ${path.config}/inputs.d/*.yml
    # Reload inputs configs as they change:
    reload.enabled: true
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true
output.logstash:
  hosts: {{ .Values.logstash.name }}:{{ .Values.logstash.port }}
  timeout: 15
{{- if .Values.elasticsearch.security.authc.enabled }}
  ssl.certificate_authorities: ["/usr/share/elasticsearch/config/tls/ca.crt"]
  ssl.certificate: "/usr/share/elasticsearch/config/tls/filebeat.crt"
  ssl.key: "/usr/share/elasticsearch/config/tls/filebeat.key"
  ssl.key_passphrase: ${APP_KEYSTORE_PASSWORD}
{{- end }}
logging.level: info
